import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export function TermsPage() {
  return (
    <div className="min-h-screen bg-ds-bg-primary"><Header /><div className="pt-24 pb-16"><div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-ds-text-primary mb-2">Terms of Service</h1><p className="text-sm text-ds-text-muted mb-10">Last updated: January 2026</p>
      <div className="space-y-8 text-sm text-ds-text-secondary leading-relaxed">
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">1. Acceptance of Terms</h2><p>By accessing and using AI Mortgage Adviser ("the Service"), you accept and agree to be bound by these Terms.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">2. AI-Generated Advice Disclaimer</h2><p>All advice provided by AI Mortgage Adviser is generated by AI and is for <strong className="text-ds-text-primary">informational purposes only</strong>. It does not constitute professional mortgage, legal, or financial advice. Always consult a qualified mortgage broker or financial adviser.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">3. Limitation of Liability</h2><p>AI Mortgage Adviser accepts <strong className="text-ds-text-primary">no responsibility</strong> for any financial decisions or consequences resulting from use of the Service. Lender recommendations are illustrative and subject to individual assessment.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">4. Payment Terms</h2><p>Full consultation costs £15 (GBP) and includes 50 questions. Monthly plan is £7/month. All payments processed via Stripe.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">5. Data Handling</h2><p>Documents are stored encrypted on AWS. We handle data in accordance with our Privacy Policy and UK GDPR.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">6. Not a Mortgage Broker</h2><p>AI Mortgage Adviser is not authorised by the FCA as a mortgage broker. We provide information and AI-generated guidance only. Any mortgage application must be made through an FCA-authorised broker or lender.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">7. Governing Law</h2><p>These Terms are governed by the laws of England and Wales.</p></section>
        <section><h2 className="text-lg font-semibold text-ds-text-primary mb-3">8. Contact</h2><p>For questions, contact <a href="mailto:support@aimortgage.co.uk" className="text-ds-text-accent hover:underline">support@aimortgage.co.uk</a></p></section>
      </div>
    </div></div><Footer /></div>
  );
}
